// packages/solid-ssr/examples/stream/index.js
import express from "express";
import url from "url";

import { renderToStream } from "solid-js/web";
import App from "../shared/src/components/App";

const app = express();
const port = 8080;

app.use(express.static(url.fileURLToPath(new URL("../public", import.meta.url))));

app.get("*", (req, res) => renderToStream(() => <App url={req.url} />).pipe(res));

app.listen(port, () => console.log(`Example app listening on port ${port}!`));

// examples/rendering/stream/index.tsx
import express from "express";
import url from "url";

import { renderToStream } from "@solidjs/web";
import Shell from "../shared/src/components/Shell";
import App from "../shared/src/components/App";
import manifest from "virtual:asset-manifest";

const app = express();
const port = 3000;

app.use(
  express.static(url.fileURLToPath(new URL("../public", import.meta.url)), {
    etag: false,
    lastModified: false,
    setHeaders: res => res.setHeader("Cache-Control", "no-store")
  })
);

app.get("*", (req, res) => {
  res.setHeader("Cache-Control", "no-store");
  renderToStream(
    () => (
      <Shell>
        <App url={req.url} />
      </Shell>
    ),
    { manifest }
  ).pipe(res);
});

app.listen(port, () => console.log(`Example app listening on port ${port}!`));
